### PR TITLE
Fill in `non_witness_utxo` when creating Spend PSBTs

### LINKED ISSUE #133: Input not recognized in the Ledger
When signing a transaction the Ledger says that input aren't recognized. We must be missing a field to set in the PSBT.

### PR DESCRIPTION
**Pull request by darosior**
Fixes #133.

### CODE REVIEW

**Comment by edouardparis** [comment]
Please do not merge until https://github.com/LedgerHQ/app-bitcoin-new/pull/89
is fixed

**Comment by darosior** [comment]
Will need to update #182 too once either it or this one is merged.

**Comment by darosior** [comment]
Rebased after the Ledger interface bug was fixed in the GUI.

**Review by edouardparis — APPROVED** [review]
ACK 07e5ea3fd2afae4e1b84abc57b0937c6e74ab3b0
tested with gui

**Pull request merged**
