### PR TITLE
Recovery command to sweep "expired" coins

### PR DESCRIPTION
**Pull request by darosior**
A new command that provides a simple way for a user to sweep all the coins whose timelocked recovery path is available.

The first part of #180. Note this also contains a number of drive-by fixes that i noticed while coding this up.

### CODE REVIEW

**Comment by darosior** [comment]
I still need to write functional tests for it. But i wanted to open the PR so @edouardparis you can start working on the GUI integration. Keep in mind it's completely untested.

**Comment by darosior** [comment]
Rebased on master following #153 (and added the `non_witness_utxo` field to recovery PSBT input), fixed a small bug in the height check and added a very basic functional test.

**Comment by edouardparis** [comment]
Sorry it is not clear what the gui can do after creating and signing the psbt. how can it finalize it and broadcast it ?

**Comment by darosior** [comment]
Nice test failure caught by CI:

```
        # Now we can create a recovery tx that sweeps the first 3 coins.
        res = lianad.rpc.createrecovery(bitcoind.rpc.getnewaddress(), 18)
        reco_psbt = PSBT.from_base64(res["psbt"])
        assert len(reco_psbt.tx.vin) == 3, "The last coin's timelock hasn't matured yet"
        assert len(reco_psbt.tx.vout) == 1
        assert int(0.5999 * COIN) < int(reco_psbt.tx.vout[0].nValue) < int(0.6 * COIN)
        txid = sign_and_broadcast(lianad, bitcoind, reco_psbt, recovery=True)
    
        # And by mining one more block we'll be able to sweep the last coin.
        bitcoind.generate_block(1, wait_for_mempool=txid)
        wait_for(
            lambda: lianad.rpc.getinfo()["block_height"] == bitcoind.rpc.getblockcount()
        )
        res = lianad.rpc.createrecovery(bitcoind.rpc.getnewaddress(), 1)
        reco_psbt = PSBT.from_base64(res["psbt"])
        assert len(reco_psbt.tx.vin) == 1
        assert len(reco_psbt.tx.vout) == 1
        assert int(0.39999 * COIN) < int(reco_psbt.tx.vout[0].nValue) < int(0.4 * COIN)
>       sign_and_broadcast(lianad, bitcoind, reco_psbt, recovery=True)

tests/test_rpc.py:587: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_framework/utils.py:83: in sign_and_broadcast
    return bitcoind.rpc.sendrawtransaction(tx)
tests/test_framework/bitcoind.py:27: in f
    return proxy.__call__(*args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test_framework.authproxy.AuthServiceProxy object at 0x7f4167fe0580>
args = ('02000000000101647134aa1771292d749dbd7967f51b7d1d22c9af95a52b897a1a4954e30e044001000000000a00000001825962020000000016...42fa58576f5e27ad655649e6be3bfa5364846c66aebff5ac736476a914c8274802ee1ec6aa582315b353e69160e3f5920088ad5ab26800000000',)
argsn = {}
postdata = '{"version": "1.1", "method": "sendrawtransaction", "params": ["02000000000101647134aa1771292d749dbd7967f51b7d1d22c9af...27ad655649e6be3bfa5364846c66aebff5ac736476a914c8274802ee1ec6aa582315b353e69160e3f5920088ad5ab26800000000"], "id": 183}'
response = {'error': {'code': -26, 'message': 'min relay fee not met, 126 < 127'}, 'id': 183, 'result': None}
status = 500

    def __call__(self, *args, **argsn):
        postdata = json.dumps(
            self.get_request(*args, **argsn),
            default=EncodeDecimal,
            ensure_ascii=self.ensure_ascii,
        )
        response, status = self._request(
            "POST", self.__url.path, postdata.encode("utf-8")
        )
        if response["error"] is not None:
>           raise JSONRPCException(response["error"], status)
E           test_framework.authproxy.JSONRPCException: min relay fee not met, 126 < 127 (-26)

tests/test_framework/authproxy.py:179: JSONRPCException
--------------------------- Captured stdout teardown ---------------------------
Test failed, leaving directory '/tmp/lianad-tests-m6yfm67s/test_create_recovery_1' intact
Leaving base dir '/tmp/lianad-tests-m6yfm67s' as it still contains ['test_create_recovery_1']
=========================== short test summary info ============================
FAILED tests/test_rpc.py::test_create_spend - TypeError: sign_and_broadcast()...
FAILED tests/test_rpc.py::test_create_recovery - test_framework.authproxy.JSO...
========================= 2 failed, 9 passed in 54.41s =========================
```

**Comment by darosior** [comment]
> Sorry it is not clear what the gui can do after creating and signing the psbt. how can it finalize it and broadcast it ?
It cannot use the broadcastspend command

Ha! Good point. I hadn't thought about that.. Do you think we should have a `broadcastpsbt` command? That's ugly :cry:.

**Comment by edouardparis** [comment]
> Ha! Good point. I hadn't thought about that.. Do you think we should have a broadcastpsbt command? That's ugly cry.****

Yes, I think we do, but I do not think it is so ugly.
We can also replace `broadcastspend`  by `broadcastpsbt`, gui can fetch spend psbt with `listspend` and then broadcast it with `broadcastpsbt`

**Review by edouardparis — COMMENTED** [review]
Tested with the gui :+1:

**Comment by darosior** [comment]
Alright i cleaned up all the remaining underestimations both in the recovery and the Spend creation. It was nice to catch this before the release.

**Comment by darosior** [comment]
self-ACK ba994ff8ff01d04fd31ed77cf7f66e0862e68e17

**Pull request merged**
