### PR TITLE
Add loader error message

### LINKED ISSUE #134: Startup error really aren't user friendly
We shouldn't print panic backtraces on such trivial things as not being able to connect to bitcoind.

### PR DESCRIPTION
**Pull request by edouardparis**
Refac notification::warning component to use a Collapse instead of Tooltip.

close #134

### CODE REVIEW

**Comment by edouardparis** [comment]
2022-11-29T22:43:10,179439916+01:00
2022-11-29T22:43:15,219051087+01:00

**Comment by darosior** [comment]
Very nice!

**Comment by darosior** [comment]
Maybe instead:
> Failed to start Liana. Make sure `bitcoind` is running.

But is this message only displayed on a `bitcoind` connection error? Otherwise it could be misleading.

**Comment by edouardparis** [comment]
> But is this message only displayed on a bitcoind connection error?
Yes

**Review by edouardparis — COMMENTED** [review]
Self-ACK 17669547ed8716c5bba08f73067c74ba7cb9c0ab

**Pull request merged**
