### PR TITLE
Windows reproducible build

### PR DESCRIPTION
**Pull request by darosior**
Using Docker for now. I'll add documentation once i've figured out macOS.

### CODE REVIEW

**Comment by edouardparis** [comment]
Will you add a docker section to doc/BUILD.md ?

**Comment by edouardparis** [comment]
sha256sum deter_build_target/x86_64-pc-windows-gnu/release/liana-gui.exe 
4cc3f1a629f9e934398cd67dfd9d4d3ccf8ac148d78dbba1eaae2269ed69b299  deter_build_target/x86_64-pc-windows-gnu/release/liana-gui.exe

**Comment by darosior** [comment]
> Will you add a docker section to doc/BUILD.md ?

I don't think so, since this isn't for regular builds. I intend to add documentation in the `docker` folder as i did with Guix.

**Comment by edouardparis** [comment]
After doing it again
sha256sum deter_build_target/x86_64-pc-windows-gnu/release/liana-gui.exe
c80408d8bf79fcf888e2f6c6bf9954f255657b8982b70ec13257ba00f7a3b734  deter_build_target/x86_64-pc-windows-gnu/release/liana-gui.exe

**Comment by darosior** [comment]
Curious.. I had pretty reproducible builds locally. Trying again..

**Comment by darosior** [comment]
Alright, this should be it. It was the timestamps from the [PE format](https://en.wikipedia.org/wiki/Portable_Executable). I started by stripping them using [`ducible`](https://github.com/jasonwhite/ducible/) but then fanquake pointed me to `ld`'s `--no-insert-timestamps` option.

Re-building from scratch now. Will let you know my hashes.

**Comment by darosior** [comment]
```
sha256sum deter_build_target/x86_64-pc-windows-gnu/release/liana-gui.exe 
3187eca3de1b8dc7acb2f9888cd3352ddf4415ed5388b0bcada139b783edb239  deter_build_target/x86_64-pc-windows-gnu/release/liana-gui.exe
```

**Comment by edouardparis** [comment]
❯ sha256sum deter_build_target/x86_64-pc-windows-gnu/release/liana-gui.exe 
3187eca3de1b8dc7acb2f9888cd3352ddf4415ed5388b0bcada139b783edb239  deter_build_target/x86_64-pc-windows-gnu/release/liana-gui.exe

**Pull request merged**
