### PR TITLE
fix various bugs with hws and spend signing process

### LINKED ISSUE #238: GUI?: Bug - hardware is connected but not found after locking/unlocking it
Trying to find the exact issue and reproduce it, will add in comments when i figure out wtf.

Screenshot from 2022-12-15 15-00-42

### LINKED ISSUE #246: GUI: in the spend process we would like a refresh button even if there is already a hardware wallet
image
I wanted to use my legder but there was no way to refresh, we need a refresh button even when another HW is connected.

### PR DESCRIPTION
**Pull request by edouardparis**
Fixes #246 
Fixes #238

### CODE REVIEW

**Comment by darosior** [comment]
I think this fixes #246?

**Comment by darosior** [comment]
And also #238

**Comment by darosior** [comment]
I've added the magic links to the OP for the two issues mentioned above. Please chime in if i was wrong.

**Comment by edouardparis** [comment]
It is good

**Review by edouardparis — COMMENTED** [review]
ACK 73eb1d38e3612110ad467fd608863519838aa988

**Pull request merged**
